baseURL = 'https://<YourUserName>.github.io/<PageName>/'
UglyURLs = true
languageCode = 'ja'
defaultContentLanguage = "ja"
title = '<PageTitle>'
hasCJKLanguage = true
summaryLength = 140
theme = '<ThemeName>'
contentDir = './episodes/'
#contentDir = './dist/hameln/'
publishDir = "docs"
relativeURLS = true
canonifyurls = true
paginate = 5
enableGitInfo = true

[permalinks]
    post = "/:year/:month/:slug"

[params]
  customCSS = ["/css/custom.css"]

[params.author]
  name = "<YourUserName>"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true

[frontmatter]
  date = [":git"]
  lastmod = [":git"]