name: Rename Novel Files

on:
  push:
    branches:
      - develop  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-18.04
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci

      - name: Episodes Build
        run: npm run novel-build-hameln -- ruby=html

      - name: Rename Install
        run: |
          sudo apt-get install rename

      - name: Rename Episodes
        run: |
          cd ./dist/hameln
          ls -la
          rename "s/txt/md/;" *.txt -f
          ls -la
      - name: Count changes
        id: changes
        run: |
          git add -N .
          echo "::set-output name=count::$(git diff --name-only | wc -l)"
      - name: commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "ci(dist/): Novel Build Hameln"
          git push
        if: steps.changes.outputs.count > 0
