name: reviewdog
on:
  pull_request:
    paths:
      - "Draft/**"
jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: textlint-github-pr-review
        uses: haoblackj/action-textlint@v1.0.7
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          textlint_flags: "Draft/**"
